
[window]
padding = { x = 3, y = 7 }
decorations = "buttonless"
opacity = 0.8

[font]
normal = { family = "PlemolJP Console", style = "Medium Italic" }
bold = { family = "PlemolJP Console", style = "Bold Italic" }
bold_italic = { family = "PlemolJP Console", style = "Bold Italic" }
italic = { family = "PlemolJP Console", style = "SemiBold Italic" }
size = 14.5
offset = { x = 0, y = 4 }

[general]
import = ["~/.config/alacritty/themes/themes/coolnight.toml"]

[terminal]

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux"]
