include ./tokyonight.conf

font_size        12

adjust_line_height 2
adjust_baseline 1

hide_window_decorations titlebar-only
window_padding_width 5
cursor_blink_interval 0
clipboard_control write-clipboard write-primary no-append
allow_remote_control yes
